### ISSUE TITLE
The old hook_update_N functions cannot be applied to Backdrop.

### ISSUE THREAD

**Issue by AlexShapka** [backdrop-contrib/coder_upgrade#20]
After I processed a Drupal 7 module with Coder Update, the `module.install` file contained the `The old hook_update_N functions cannot be applied to Backdrop.` message stripping off the function code. Checking the https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_update_N/1 page doesn't show any deprecation notice.

The original code for the function was:

```
/**
* Create database on update.
*/

function search_index_update_7100() {
 if (!db_table_exists('search_index_excluded')) {
   $schema['search_index_excluded'] = array(
     'description' => 'The base table for nodes.',
     'fields' => array(
       'nid' => array(
         'description' => 'The primary identifier for a node.',
         'type' => 'serial',
         'unsigned' => TRUE,
         'not null' => TRUE,
       ),
       'type' => array(
         'description' => 'The {node_type} of this node.',
         'type' => 'varchar',
         'length' => 32,
         'not null' => TRUE,
         'default' => '',
       ),
       'title' => array(
         'description' => 'The title of this node, always treated as non-markup plain text.',
         'type' => 'varchar',
         'length' => 255,
         'not null' => TRUE,
         'default' => '',
       ),
     ),
     'primary key' => array(
       'nid',
     ),
   );
  db_create_table('search_index_excluded', $schema['search_index_excluded']);
  }
}
```

Any suggestions for my case?

**Comment by docwilmot** [comment]
Thanks

`hook_update_N()` is used when updating a module version, like from D7 v1.2.1 to v1.2.2. They cant apply when upgrading from D7 to backdrop. You would need to run all D7 updates before you upgrade to backdrop.

I considered having Coder Upgrade just delete them completely but thought it *may* be useful just to leave that message there so you known the functions existed before the Upgrade, in case something went wrong. Something going wrong due to those functions is highly unlikely though, so will probably just make Coder delete those `hook_update_N()` implementations in a future version.

For now, don't worry about those, just delete them manually after the upgrade.
