### ISSUE TITLE
Use config()->delete() instead of config_clear() in .install file

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/coder_upgrade#21]
Please read https://github.com/backdrop/backdrop-issues/issues/4186#issuecomment-548943960 to see that replacing Drupal 7's `variable_del()` function in `.install` files is not sufficient. Either `config_clear()` should be used in the .module file to declare variables and then the `variable_del()` function in .install should be dropped, or the following function:

```
/**
 * Implements hook_uninstall().
 */
function $mymodule_uninstall() {
  config('mymodule.settings')->delete();
}
```

should be used instead to get the uninstalled module's configuration file actually deleted.

**Comment by bugfolder** [comment]
The call to `config('mymodule.settings')->delete()` is superfluous. If a module's config file is properly declared by `hook_config_info()`, then it will be automatically deleted when the module is uninstalled.

Prior to 2021-03-14, there was a bug in the automatic generation of `hook_config_info()` that resulted in the config file not being properly declared, and thus, being left as a residue when the module was uninstalled. See https://github.com/backdrop-contrib/coder_upgrade/issues/28 and associated PR.

Since this comment was written prior to that, that would explain the behavior reported in the comment above. But it's now been fixed.
