### ISSUE TITLE
Installing gives Error: syntax error, unexpected '$domain' (T_VARIABLE)

### ISSUE THREAD

**Issue by LeeteqXV** [backdrop-contrib/coder_upgrade#25]
I have tried both the latest coder_upgrade version (1.x-1.x) from github, and the 1.x-1.0.2-beta from backdrop modules page, both gives the following error on installation (and no coder admin page links appear in the menu): "Error: syntax error, unexpected '$domain' (T_VARIABLE)"
(I am installing to (the root of...) a subdomain, not the root of the main domain (without www) nor to "www", if that is relevant, since the error says "unexpected domain".)

Initially after the installation error, there seem not to be any menu created for the URL "admin/config/development/coder-upgrade" , but not sure if I was tired yesterday. Anyway, coming back to the site now today and manually trying to go to admin/config/development/coder-upgrade by pasting it in the url, then the coder module is there/available/ready, and now the link in the Configuration - Development menu is also in place.

But the error message is displayed on a "white screen" with only that message, so at least the first impression is that the installation failed.

I will try to use it and report back here if it is actually working.

**Comment by sternhagel** [comment]
I'm seeing the same error message, though not on installation but on trying to use the module.

After starting a conversion, it says:
> Module conversion routines will run in the same process. 
syntax error, unexpected '$domain' (T_VARIABLE)

In the error log there is the following message:

> ParseError: syntax error, unexpected '$domain' (T_VARIABLE) in module_load_include() (line 165 of [...]/modules/youtube/modules/youtube_colorbox/youtube_colorbox.module).

...which is weird because the YouTube module isn't even activated, and it's not part of the code I'm trying to convert.

**Comment by olafgrabienski** [comment]
> which is weird because the YouTube module isn't even activated, and it's not part of the code I'm trying to convert

@sternhagel I guess *Coder Upgrade* tried to convert all modules, see https://github.com/backdrop-contrib/coder_upgrade/issues/27.

**Comment by olafgrabienski** [comment]
> I guess Coder Upgrade tried to convert all modules, see #27.

Nope, even after double checking that only the relevant checkboxes of *Coder upgrade* are enabled, I get the same error when the *Youtube* module is on the site.

**Comment by bugfolder** [comment]
Pretty sure this is an effect of the same bug that was causing https://github.com/backdrop-contrib/coder_upgrade/issues/59. There's a call that is supposed to load all disabled core modules, and because of a missed change in where modules live, it was trying to load all disabled contrib modules. That's now fixed, so I'm closing this issue.

 If you still see it, though, please re-open this issue, of course!
